### ISSUE TITLE
dyld: Symbol not found: __T0BOWV XCode 10

### ISSUE THREAD

**Issue by amit-pandey11** [voxeet/voxeet-ios-sdk#1]
We are facing an issue with SDK on XCode 10: it says :
![screen shot 2018-09-21 at 12 40 20 pm](https://user-images.githubusercontent.com/31159792/45866205-aa54cf00-bd9d-11e8-88d2-2c060fa6d226.png)
Hope this issue is only on XCode 10.

**Comment by Comanga** [comment]
This should be fix with the https://github.com/voxeet/voxeet-ios-sdk/releases/tag/1.2.1 version which supports iOS 12 / Swift 4.2 / Xcode 10.

**Comment by amit-pandey11** [comment]
Thank you for the response.
I am using VoxeetSDK via Pod so how can I use this framework with existing one should need to update my Pod to any specific version or I need to add voxeet manually?

**Comment by Comanga** [comment]
I need to update the documentation but one other thing, we stopped supporting simulator architecture.

You can test the framework with the Sample https://github.com/voxeet/voxeet-ios-conferencekit/tree/master/Sample (don't forget to do a `carthage update --platform ios`).

**Comment by amit-pandey11** [comment]
I have remove pod and installed it manually but now it is not working on the device it says:
![screen shot 2018-09-21 at 5 23 31 pm](https://user-images.githubusercontent.com/31159792/45879773-53fa8700-bdc3-11e8-9404-830d8802dea3.png)

Thank you in advance.

**Comment by Comanga** [comment]
Are you testing on the Sample?
Have you correctly setted the signing section with your **team**?

<img width="868" alt="screen shot 2018-09-21 at 2 02 18 pm" src="https://user-images.githubusercontent.com/6548634/45880147-49ca8f80-bda7-11e8-892a-4117f9c1494b.png">

**Comment by amit-pandey11** [comment]
No, I am not testing it with the sample I am integrating it in my project, where the sign in section is filled correctly.

**Comment by Comanga** [comment]
Maybe try a clean? cmd+shift+k and cmd+alt+shift+k to clean derived data

**Comment by amit-pandey11** [comment]
I have tried it but nothing works.

**Comment by Comanga** [comment]
Can you restart your Xcode and test the VoxeetSDK Sample just to check if it's a bad implementation or something?

**Comment by amit-pandey11** [comment]
I cleaned the project and tried to close and reopen Xcode but nothing works. May I know in how much time we will get the support of cocoa pod? I guess which will solve this issue.

**Comment by Comanga** [comment]
Try the Sample please (it uses Carthage) and tell me if you have the same issue.

CocoaPods is not on the roadmap for now, I can't give you a date.

**Comment by amit-pandey11** [comment]
I tried it, its working fine. I have just updated the Carthage and it works on my device. But in my project I can not use Carthage, I have installed it manually where I have just downloaded the framework from the given link and dragged VoxeetSDK.framework and WebRTC.framework to my project and then added them to embedded Binaries. But this whole process for my project doesn't work it started giving the above error.
Is there any mistake in my manual integration?

**Comment by Comanga** [comment]
No mistakes you did the manual integration right. 

I don't really know where your issue came from.
I just tried to download the Sample from this repo, remove Carthage support and download the SDK from this link https://github.com/voxeet/voxeet-ios-sdk/releases/tag/1.2.1, manually install it by copying the frameworks and embed both of them and it's working fine.

It looks like a weird Xcode issue.

**Comment by Comanga** [comment]
Great news.

Yes, we don't support simulator environment on our latest release due to the current WebRTC framework...
It's not on the road map for now, can you use a device?

**Comment by amit-pandey11** [comment]
Yes, but you know its more comfortable to use simulators for the development. ;)

**Comment by amit-pandey11** [comment]
Thank you for the support.

**Comment by Comanga** [comment]
I know :)
You're welcome.
