### ISSUE TITLE
Profiling with XCode Instruments found some leaked objects in sample app (sdk 1.3.0)

### ISSUE THREAD

**Issue by chanonly123** [voxeet/voxeet-ios-sdk#10]
Attached Video shows single call with 2 participants. There are some leaked objects detected by the XCode Instruments tool.
 
[Link to video](https://drive.google.com/file/d/1Qo1FSRTLCE2Xs5HH4mxYe7oC_j8hcP8_/view?usp=sharing)

**Comment by VTCoco** [comment]
Thank's, working on it.

**Comment by VTCoco** [comment]
This should be fix in the 1.3.1 release :)
