### ISSUE TITLE
cocoapod error

### ISSUE THREAD

**Issue by caglarcakar** [voxeet/voxeet-ios-sdk#11]
**Describe the bug**

I am getting "VoxeetSDK compiled with older version of Swift language" error if I add sdk with cocoapod. I tried to build with both swift 4 and swift 5 but the same. 

**Steps to Reproduce the Problem**

  1. add pod 'VoxeetSDK'
  2. Pod update
  3. Build the project

**Minimalistic code (recommended)**

ld: /Users/***/ProjectName/Pods/VoxeetSDK/VoxeetSDK/VoxeetSDK.framework/VoxeetSDK compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file '/Users/***/ProjectName/Pods/VoxeetSDK/VoxeetSDK/VoxeetSDK.framework/VoxeetSDK' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Specifications**

  - Device: Macbook pro
  - OS: MacOS 10.14.5
  - Platform: Xcode 10.2.1
  - Subsystem: Cocoapod 1.6.1
  - Version:
    - VoxeetSDK (1.1.2)

**Comment by codlab** [comment]
This SDK is outdated. Please update to the latest version of the SDK directly from this repository in the releases tab:

https://github.com/voxeet/voxeet-ios-sdk/releases

If you are also using the ConferenceKit, you can check them directly here:
https://github.com/voxeet/voxeet-ios-conferencekit/releases

**Comment by caglarcakar** [comment]
You probably build the file "VoxeetSDK.framework.zip" with debug options, it gives unsupported architecture x86_64 i386 error 😕

**Comment by codlab** [comment]
I'm closing this issue. Please reopen a new one with more information about it. @VTCoco will be able to gie more information about the use of devices instead of emulators

**Comment by VTCoco** [comment]
Hello @caglarcakar, this compilation issue will be patched in the next release in few days.It's a known Xcode compilation issue from 10.2.1 (the SDK is already compiled with release option).
If you want more information, please open a new ticket that can help other peoples.

**Comment by VTCoco** [comment]
Only Objective-C projects compiled with simulator are affected (Cordova uses ObjC).

**Comment by caglarcakar** [comment]
No, my project is pure swift. The solution I found : [https://stackoverflow.com/questions/30547283/submit-to-app-store-issues-unsupported-architecture-x86/39489491](url)

**Comment by VTCoco** [comment]
You were talking about pushing (archiving) an app with VoxeetSDK.
If you aren't using Carthage, yes you need to strip VoxeetSDK framework to remove simulators architectures.
For example you can implement a script that automatically strip VoxeetSDK like this post: https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive
