### ISSUE TITLE
How to enable/disable mute button which is under VoxeetConferenceKit SDK?

### ISSUE THREAD

**Issue by Ashish1112** [voxeet/voxeet-ios-sdk#12]
How to enable/disable mute button which is under VoxeetConferenceKit SDK?

If you have any idea regarding this point then please me to sort out this issue because i am stuck to do that

Thanks in advance

**Comment by VTCoco** [comment]
I'm not really sure to understand your question.
Do you want to hide the mute button from the bottom bar? Or let it visible but toggle its state to "disable" (grey button that can't be clicked)?

**Comment by Ashish1112** [comment]
I want to hide only mute button from the bottom bar and also i want user interaction disable of speaker button.

**Comment by VTCoco** [comment]
Make sure to have the last VoxeetConferenceKit version which have a configuration object (1.2.2) and the last VoxeetSDK (1.4.4).
So you can hide buttons from the action bar (mute, speaker, ...) and also override buttons' images according to your design. However you can't disable the speaker button (you can fork the open source VoxeetConferenceKit project and do what you want).

Here is an example how to hide the mute button:

```swift
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Voxeet frameworks initialization.
        VoxeetSDK.shared.initialize(consumerKey: "YOUR_CONSUMER_KEY", consumerSecret: "YOUR_CONSUMER_SECRET")
        VoxeetConferenceKit.shared.initialize()
        
        // Example of public variables to change the conference behavior.
        VoxeetSDK.shared.pushNotification.type = .callKit
        VoxeetSDK.shared.conference.defaultBuiltInSpeaker = true
        VoxeetSDK.shared.conference.defaultVideo = false
        
        // Example of UXKit configuration.
        let config = VoxeetConferenceKit.shared.conferenceController?.configuration
        config?.actionBar.displayMute = false /* HIDE MUTE BUTTON */
        
        return true
    }
```

**Comment by Ashish1112** [comment]
I've one more question regarding this 

When we create conference call that time how we can disable user interaction of mute button?

Can you please help me to sort out that issue

Thanks in advance

**Comment by Ashish1112** [comment]
Do you have any solution then please let me know

Thanks

**Comment by VTCoco** [comment]
The only solution is to hide the mute button for now. Your case don't seem to fit with a basic conference behaviour.
As a reminder you can fork the UI to accomplish what you want (https://github.com/voxeet/voxeet-ios-conferencekit).

And this question is more related to the ConferenceKit project so it's preferable to open an issue on this one https://github.com/voxeet/voxeet-ios-conferencekit/issues thank you.

**Comment by Ashish1112** [comment]
Ok thanks for your support
