### ISSUE TITLE
Leave conference Failed With Call kit error: Please Help

### ISSUE THREAD

**Issue by w3b-amit** [voxeet/voxeet-ios-sdk#14]
We use voxeet with the Call kit. Most of the time when we end an incoming call this error come in leave conference callback block.

> ^^^^^^^^^^^^^^^^^^^^^^ VOXEET: Conference leaved Failed : Error Domain=com.apple.CallKit.error.requesttransaction Code=4 "(null)" ^^^^^^^^^^^^^^^^

Please Look into this because due to this the call kit never ends and we need to kill the app to remove the call kit also due to this we are not able to make any other call from the app.
@Comanga @VTCoco @codlab @4thlabs

**Comment by VTCoco** [comment]
Hello @w3b-amit, what is your VoxeetSDK version please?
I can't reproduce your issue for now, do you have a specific flow so I can have the same behaviour on my side? (does the application was on foreground, background... for example)

**Comment by VTCoco** [comment]
Due to inactivity this issue will be closed. Feel free to reopen it if you have any news @w3b-amit.
