### ISSUE TITLE
Need CocoaPods for Latest Voxeet iOS SDK.

### ISSUE THREAD

**Issue by hafiz-mohsin-confiz** [voxeet/voxeet-ios-sdk#16]
As you guys are providing the Carthage support for Voxeet iOS SDK, Is there a CocoaPods library link available for Latest Voxeet iOS SDK?
As following link is your old Cocoa Pods Library Link:
https://cocoapods.org/pods/VoxeetSDK
Looking forward to your response.

**Comment by VTCoco** [comment]
CocoaPods was supported one year ago.
We need to work again on it but we are facing a file size problem with GitHub to embed all iOS architectures. So when this issue will be fixed we will support it again.

**Comment by hafiz-mohsin-confiz** [comment]
Hi Vooxet Team,
I have also faced a file size problem in GitHub as you mentioned. I have solved the file size problem with following the Github feature i-e LFS(Large File Storage).

Reference LInk: https://git-lfs.github.com/

Now you can push the big file on Github apart from its 100 MB file size limit.
Thanks,

**Comment by VTCoco** [comment]
Thank you for the link!

**Comment by VTCoco** [comment]
Hello @hafiz-mohsin-confiz, CocoaPods support is coming back! :)

**Comment by hafiz-mohsin-confiz** [comment]
Thanks for your effort & support.

**Comment by VTCoco** [comment]
Hello @hafiz-mohsin-confiz, just for information the Voxeet UXKit is also compatible with CocoaPods if you want to embed the SDK with a ready to go UI (https://github.com/voxeet/voxeet-uxkit-ios). :)
Just add `pod 'VoxeetConferenceKit'` to your Podfile (note: it will be renamed VoxeetUXKit in the next release).
