### ISSUE TITLE
How to stop any running conference

### ISSUE THREAD

**Issue by Comanga** [voxeet/voxeet-ios-sdk#3]
How to stop any running conference? 
Is there any specific code or method to do so?

_Originally posted by @amit-pandey11 in https://github.com/voxeet/voxeet-ios-sdk/issues/2#issuecomment-426897747_

**Comment by Comanga** [comment]
You can check if there is a current live conference first (in Swift):

`let conferenceID = VoxeetSDK.shared.conference.id`

If the conferenceID above is different than nil, it means there is a running conference.
Then you can leave it with this method: https://github.com/voxeet/voxeet-ios-sdk#leaving-a-conference

**Comment by amit-pandey11** [comment]
There is some error in Joining conference. 
This my code to join Conference and place call:
`[[[VoxeetSDK shared] conference] createWithParameters:callData success:^(NSDictionary<NSString *,id> * _Nullable conference) {
        
        NSLog(@"^^^^^^^^^^^^^^^^^^ VOXEET: Conference created Successfully ^^^^^^^^^^^^^^^^");
        
        if (conference) {
            
            NSLog(@"Conference: %@", conference);
            
            [[[VoxeetSDK shared] conference] inviteWithConferenceID:conference[@"conferenceId"] ids:@[@"10310"] completion:^(NSError * _Nullable error) {
                
                if (error) {
                    NSLog(@"^^^^^^^^^ VOXEET: Error in Inviting ^^^^^^^^^^^^^^");
                } else {
                    
                    NSLog(@"^^^^^^^^^ VOXEET: Invitation Sent ^^^^^^^^^^^^^^");
                    
                    [[[VoxeetSDK shared] conference] joinWithConferenceID:[[[VoxeetSDK shared] conference] id] video:NO userInfo:nil success:^(NSDictionary<NSString *,id> * _Nullable conference) {
        
        NSLog(@"^^^^^^^^^^^^^^^^ VOXEET: Conference Joind : %@ ^^^^^^^^^^^^^^^^^^", conference);
        
    } fail:^(NSError * _Nonnull error) {
        
        NSLog(@"^^^^^^^^^^^^^^^^ VOXEET: Conference Failed to Join : %@ ^^^^^^^^^^^^^^^^^^", error);
        
    }];
                    
                }
                
            }];
            
        }
        
    } fail:^(NSError * _Nonnull error) {
        
        NSLog(@"^^^^^^^^^^^^^^^^^^ VOXEET: Conference Failed To Create ^^^^^^^^^^^^^^^^^^:%@", error);
        [self unregisterAllVoxeetCallHandlers];
        
    }];`

I am not getting any response or error on calling JoinConference Method.
And when I force this join method again then I get this error message in console:
`VOXEET: Conference Failed to Join : Error Domain=com.apple.CallKit.error.requesttransaction Code=7 "(null)"`

Please look into my issue.

**Comment by Comanga** [comment]
Can you print me the NSLogs bellow so I can check the flow please?

And join with conference[@"conferenceId"] instead of [[[VoxeetSDK shared] conference] id] (can be null), and you can also remove all `_Nullable`.

**Comment by amit-pandey11** [comment]
It worked. Thank You for the response.
