### ISSUE TITLE
Call Recording: We need sample Call recording webhook response

### ISSUE THREAD

**Issue by amit-pandey11** [voxeet/voxeet-ios-sdk#4]
Hello Team,
We are using Voxeet SDK to make dedicated calls with the feature of call recording. For this, we need a sample response of a webhook which get called on call end.
Thank You.

**Comment by Comanga** [comment]
https://github.com/voxeet/web-sdk-sample/issues/2

**Comment by amit-pandey11** [comment]
we got this response in webhook:
object(WP_REST_Request)#869 (8) {
  ["method":protected]=>
  string(4) "POST"
  ["params":protected]=>
  array(6) {
    ["URL"]=>
    array(0) {
    }
    ["GET"]=>
    array(0) {
    }
    ["POST"]=>
    array(0) {
    }
    ["FILES"]=>
    array(0) {
    }
    ["JSON"]=>
    array(9) {
      ["confId"]=>
      string(36) "e9f63eb0-0bc9-454c-b590-08cce5e2d552"
      ["confAlias"]=>
      string(9) "495760765"
      ["confType"]=>
      string(8) "SDK_CONF"
      ["ownerId"]=>
      string(36) "963c8c7d-3b5d-43c9-a608-3c0517eded46"
      ["startTime"]=>
      int(1538984801473)
      ["duration"]=>
      int(234971)
      ["speakingDuration"]=>
      int(227425)
      ["recordingDuration"]=>
      int(227822)
      ["participants"]=>
      array(2) {
        [0]=>
        array(6) {
          ["userId"]=>
          string(36) "963c8c7d-3b5d-43c9-a608-3c0517eded46"
          ["ipAddress"]=>
          string(14) "103.210.44.130"
          ["presenceDuration"]=>
          int(231522)
          ["recvTimers"]=>
          array(1) {
            ["AUDIO"]=>
            int(219508)
          }
          ["sendTimers"]=>
          array(1) {
            ["AUDIO"]=>
            int(223398)
          }
          ["metadata"]=>
          array(3) {
            ["externalPhotoUrl"]=>
            string(81) "##########/ev_36053_1528280674.jpg"
            ["externalId"]=>
            string(5) "36053"
            ["externalName"]=>
            string(3) "Ami"
          }
        }
        [1]=>
        array(6) {
          ["userId"]=>
          string(36) "04212edc-6eeb-4136-9e4b-e1b612373a13"
          ["ipAddress"]=>
          string(14) "103.210.44.130"
          ["presenceDuration"]=>
          int(230013)
          ["recvTimers"]=>
          array(1) {
            ["AUDIO"]=>
            int(223560)
          }
          ["sendTimers"]=>
          array(1) {
            ["AUDIO"]=>
            int(226014)
          }
          ["metadata"]=>
          array(3) {
            ["externalPhotoUrl"]=>
            string(88) "#############/ev_expert_10310_1538061836.jpg"
            ["externalId"]=>
            string(5) "10310"
            ["externalName"]=>
            string(15) "EngVarta Expert"
          }
        }
      }
    }
    ["defaults"]=>
    array(0) {
    }
  }
  ["headers":protected]=>
  array(6) {
    ["content_type"]=>
    array(1) {
      [0]=>
      string(16) "application/json"
    }
    ["content_length"]=>
    array(1) {
      [0]=>
      string(3) "923"
    }
    ["user_agent"]=>
    array(1) {
      [0]=>
      string(16) "ReactorNetty/dev"
    }
    ["transfer_encoding"]=>
    array(1) {
      [0]=>
      string(7) "chunked"
    }
    ["host"]=>
    array(1) {
      [0]=>
      string(21) "##########.com"
    }
    ["accept"]=>
    array(1) {
      [0]=>
      string(3) "*/*"
    }
  }
  ["body":protected]=>
  string(923) "{"confId":"e9f63eb0-0bc9-454c-b590-08cce5e2d552","confAlias":"495760765","confType":"SDK_CONF","ownerId":"963c8c7d-3b5d-43c9-a608-3c0517eded46","startTime":1538984801473,"duration":234971,"speakingDuration":227425,"recordingDuration":227822,"participants":[{"userId":"963c8c7d-3b5d-43c9-a608-3c0517eded46","ipAddress":"103.210.44.130","presenceDuration":231522,"recvTimers":{"AUDIO":219508},"sendTimers":{"AUDIO":223398},"metadata":{"externalPhotoUrl":"##########/ev_36053_1528280674.jpg","externalId":"36053","externalName":"Ami"}},{"userId":"04212edc-6eeb-4136-9e4b-e1b612373a13","ipAddress":"103.210.44.130","presenceDuration":230013,"recvTimers":{"AUDIO":223560},"sendTimers":{"AUDIO":226014},"metadata":{"externalPhotoUrl":#########/ev_expert_10310_1538061836.jpg","externalId":"10310","externalName":"EngVarta Expert"}}]}"
  ["route":protected]=>
  string(20) "/w3/v1/voxeetWebhook"
  ["attributes":protected]=>
  array(6) {
    ["methods"]=>
    array(1) {
      ["POST"]=>
      bool(true)
    }
    ["accept_json"]=>
    bool(false)
    ["accept_raw"]=>
    bool(false)
    ["show_in_index"]=>
    bool(true)
    ["args"]=>
    array(0) {
    }
    ["callback"]=>
    string(13) "voxeetWebhook"
  }
  ["parsed_json":protected]=>
  bool(true)
  ["parsed_body":protected]=>
  bool(false)
}

But in this webhook, we don't get the Recording URL that we need to save on our server side?

**Comment by codlab** [comment]
Hi,

Your last message seems to be exclusively related to an issue you opened
earlier into the web sample repository. To make sure you have a reliable
and proper answer please post it there.

https://github.com/voxeet/web-sdk-sample/issues

Le mar. 9 oct. 2018 à 07:49, Amit Pandey <notifications@github.com> a
écrit :

**Comment by amit-pandey11** [comment]
Sure.
