### ISSUE TITLE
Skipped installing voxeet-ios-conferencekit.framework binary due to the error: 	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1).

### ISSUE THREAD

**Issue by karthinalliyappan** [voxeet/voxeet-ios-sdk#6]
While install frameworks using cart file getting the below error
"Skipped installing voxeet-ios-conferencekit.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)."

    Falling back to building from the source
***  Skipped installing voxeet-ios-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)."

Development Tools Version:
Operating systems: iOS 10.3.2 
IDE: Xcode 10.0

Attached the screen shot for reference:

![screen shot 2018 11 19 at 10 07 23 am](https://user-images.githubusercontent.com/26541759/48686779-d779fe00-ebe3-11e8-9c02-a68ebfb3b35c.png)

**Comment by codlab** [comment]
Please update your Xcode environment.
