### ISSUE TITLE
Call kit not presented even voip push arrived

### ISSUE THREAD

**Issue by RishishPandey** [voxeet/voxeet-ios-sdk#7]
Hi, I am looking at this log - I notice the voip push was sent from voxeet for an incoming call but the call kit was not presented.  I noticed it happened twice today. Please look into it. I am attaching the log of the last incident.

[-.txt](https://github.com/voxeet/voxeet-ios-sdk/files/2830742/-.txt)

**Comment by codlab** [comment]
Wrong issue template. Closed
