### ISSUE TITLE
Crashing WebRTC RTCFileName

### ISSUE THREAD

**Issue by chanonly123** [voxeet/voxeet-ios-sdk#8]
Got this crash report from Crashlytics, Voxeet sdk version 1.2.8

[com.getopentalk.opentalk_issue_241_crash_b3772bb8095c426da06a01196bde8ce5_DNE_0_v2.txt](https://github.com/voxeet/voxeet-ios-sdk/files/2836203/com.getopentalk.opentalk_issue_241_crash_b3772bb8095c426da06a01196bde8ce5_DNE_0_v2.txt)

**Comment by codlab** [comment]
Wrong issue template. Closed
